using System.Collections.Generic;

namespace Keycloak.ASPNet.Angular.Api.Models;

/// <summary>
/// Global roles container.
/// </summary>
/// <autogeneratedoc />
public class ZitadelJwtResourceRoles : Dictionary<string, Dictionary<string, string>>
{
}